/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_visualogyx_activity_MyNDK */

#ifndef _Included_com_visualogyx_activity_MyNDK
#define _Included_com_visualogyx_activity_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_visualogyx_activity_MyNDK
 * Method:    processImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_visualogyx_activity_MyNDK_processImage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
